os: linux
dist: trusty
sudo: required
services:
  - docker

install:
 - docker pull ubuntu:18.04

script:
 - docker run -v $(pwd):/liftinstall ubuntu:18.04 /bin/bash -ex /liftinstall/.travis/build.sh
